var app;

app = angular.module("plunker", ["colorpicker.module", "chartjs.directive"]);

"use strict";


/*
 @name - FormItem
 @comment - This creates a form control group.
 @usage <formitem title="Label:" type="text">[Contents]</box>
 */

app.directive("formitem", function() {
  var postLink;
  return {
    restrict: "E",
    replace: true,
    transclude: true,
    scope: {
      title: "@",
      name: "@",
      help: "@",
      placeholder: "@"
    },
    link: postLink = function(scope, element, attrs) {
      element.find('input').addClass('input-medium');
      return console.log(element);
    },
    template: '<div class="control-group">\n  <div class="control-label">\n    <label for="{{name}}" id="{{name | lowercase}}">{{title}}</label>\n  </div>\n  <div class="controls" ng-transclude></div>\n  <span class="inline-help">{{help}}</span>\n</div>'
  };
});

app.controller("MainCtrl", function($scope, $rootScope) {
  var options;
  $scope.defaults = {
    bar: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      datasets: [
        {
          fillColor: "rgba(220,220,220,0.5)",
          strokeColor: "rgba(220,220,220,1)",
          pointColor: "rgba(220,220,220,1)",
          pointStrokeColor: "#fff",
          data: [65, 59, 90, 81, 56, 55, 40]
        }, {
          fillColor: "rgba(151,187,205,0.5)",
          strokeColor: "rgba(151,187,205,1)",
          pointColor: "rgba(151,187,205,1)",
          pointStrokeColor: "#fff",
          data: [28, 48, 40, 19, 96, 27, 100]
        }
      ]
    },
    line: {},
    pie: {},
    radar: {
      labels: ["Eating", "Drinking", "Sleeping", "Designing", "Coding", "Partying", "Running"],
      datasets: [
        {
          fillColor: "rgba(220,220,220,0.5)",
          strokeColor: "rgba(220,220,220,1)",
          pointColor: "rgba(220,220,220,1)",
          pointStrokeColor: "#fff",
          data: [65, 59, 90, 81, 56, 55, 40]
        }, {
          fillColor: "rgba(151,187,205,0.5)",
          strokeColor: "rgba(151,187,205,1)",
          pointColor: "rgba(151,187,205,1)",
          pointStrokeColor: "#fff",
          data: [28, 48, 40, 19, 96, 27, 100]
        }
      ]
    },
    doughnut: {}
  };
  $scope.chart = {
    title: "Chart",
    type: "Bar",
    height: 250,
    width: 600,
    options: {
      chart: {
        events: {
          selection: function(e) {
            return console.log(e);
          }
        }
      }
    },
    data: null
  };
  $scope.chart.data = $scope.defaults[String($scope.chart.type).toLowerCase()];
  options = {};
  $scope.Chartjs = {
    addItem: function(o) {
      return $scope.$apply(function() {
        return $scope.chart.data.datasets[0].data.push(obj);
      });
    }
  };
  return angular.element(document).ready(function() {
    return angular.element("legend").bind("click", function() {
      return angular.element(this).next().slideToggle();
    });
  });
});

// ---
// generated by coffee-script 1.9.2
